services:
  vprofile-svc:
    image: loulah/vprofile
    ports:
      - "8080:8080"
    networks:
      app-network:
    depends_on:
      - mysql-service
      - memcache-svc
      - rabbitmq-svc

  mysql-service:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      app-network:
  memcache-svc:
    image: memcached:trixie    
    networks:
      app-network:

  rabbitmq-svc:
    image: rabbitmq:management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
    networks:
      app-network:
  nginx-svc:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      app-network:
    ports:
      - "80:80"
    depends_on:
      - vprofile-svc
    
networks:
  app-network:
volumes:
  mysqldata:
  