
# -------------------------------
# vprofile (Maven)
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile-dep
  namespace: vprofile-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprofile-dep-pod
  template:
    metadata:
      labels:
        app: vprofile-dep-pod
    spec:
      containers:
        - name: vprofile
          image: loulah/vprofile:latest  # <-- replace with your Flask vprofile image
          ports:
            - containerPort: 8080
          resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: vprofile-svc
  namespace: vprofile-app
spec:
  type: NodePort
  selector:
    app: vprofile-dep-pod
  ports:
    - port: 8080
      targetPort: 8080