# -------------------------------
# vprofile (Maven)
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Namespace }}-vprofile
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprofile-dep-pod
  template:
    metadata:
      labels:
        app: vprofile-dep-pod
    spec:
      containers:
        - name: vprofile
          image: {{ .Values.images.vp.name }}:{{ .Values.images.vp.tag }} # loulah/vprofile:latest 
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Namespace }}-vprofile-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: vprofile-dep-pod
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32004
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{.Release.Namespace}}
data:
  JDBC_URL: jdbc:mysql://{{.Release.Namespace}}-mysql-svc.{{.Release.Namespace}}.svc.cluster.local:3306/accounts
  MEMCACHED_ACTIVE_HOST: {{ .Release.Namespace }}-memcache-svc.{{.Release.Namespace}}.svc.cluster.local
  MEMCACHED_STANDBY_HOST: {{ .Release.Namespace }}-memcache-svc.{{.Release.Namespace}}.svc.cluster.local
  RABBITMQ_ADDRESS: {{ .Release.Namespace }}-rabbitmq-svc.{{.Release.Namespace}}.svc.cluster.local